export const initialFormData = {
  general: [0, 1, 2],
  education: [3, 4, 5],
  work: [6, 7, 8, 9, 10],
  0: { id: 0, label: "name", type: "text", value: "" },
  1: { id: 1, label: "email", type: "text", value: "" },
  2: { id: 2, label: "phone number", type: "tel", value: "" },
  3: { id: 3, label: "school", type: "text", value: "" },
  4: { id: 4, label: "major", type: "text", value: "" },
  5: { id: 5, label: "graduation date", type: "date", value: "" },
  6: { id: 6, label: "company", type: "text", value: "" },
  7: { id: 7, label: "position", type: "text", value: "" },
  8: { id: 8, label: "responsibilities", type: "text", value: "" },
  9: { id: 9, label: "start date", type: "date", value: "" },
  10: { id: 10, label: "end date", type: "date", value: "" },
};
